# Generated by Django 5.1 on 2024-08-24 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='firma', max_length=50)),
                ('contactname', models.CharField(default='contact', max_length=50)),
                ('address', models.CharField(default='address', max_length=50)),
                ('phone', models.CharField(default='phone', max_length=50)),
                ('email', models.EmailField(default='email', max_length=50)),
                ('country', models.CharField(default='country', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='productname', max_length=50)),
                ('packagesize', models.CharField(default='packagesize', max_length=50)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unitsinstock', models.IntegerField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
        ),
    ]
